# Generated by Django 5.2.4 on 2025-07-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
